
#
# Configuration
#
language: cpp
dist: trusty

#
# Build Dependencies
#
before_script:

  #
  # Build Folder
  #
  - mkdir build
  - cd build

  #
  # Update / Install CMake
  #
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p external/cmake
      pushd external/cmake
      wget https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.sh
      chmod +x cmake-*-Linux-x86_64.sh
      ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
      export PATH="${PWD}/bin:$PATH"
      popd
    else
      if ! brew ls --version cmake &>/dev/null; then brew update; brew install cmake; fi
    fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - xorg-dev
      - libglu1-mesa-dev

#
# Build Matrix
#
matrix:
  include:

  #
  # Git Check
  #
  - os: linux
    env:
      - TEST="Git Check"
    script:
      - |
        if [[ -n $(git diff --check HEAD^) ]]; then
          echo "You must remove whitespace before submitting a pull request"
          echo ""
          git diff --check HEAD^
          exit -1
        fi
  #
  # Astyle Format
  #
  # - os: linux
  #   env:
  #     - TEST="Astyle Format"
  #   addons:
  #     apt:
  #       sources:
  #         - ubuntu-toolchain-r-test
  #         - llvm-toolchain-trusty-4.0
  #       packages:
  #         - gcc-7
  #         - g++-7
  #   script:
  #     - cmake -DENABLE_ASTYLE=ON -DCMAKE_CXX_COMPILER="g++-7" ..
  #     - make
  #     - make format
  #     - |
  #       if [[ -n $(git diff) ]]; then
  #         echo "You must run make format before submitting a pull request"
  #         echo ""
  #         git diff
  #         exit -1
  #       fi

  #
  # G++ 7.1
  #
  - os: linux
    env:
      - TEST="G++ 7.1"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-4.0
        packages:
          - gcc-7
          - g++-7
          - xorg-dev
          - libglu1-mesa-dev
    script:
      - cmake -DCMAKE_CXX_COMPILER="g++-7" ..
      - cmake --build . --config Release

  #
  # Clang 4.0
  #
  # - os: linux
  #   env:
  #     - TEST="Clang 4.0"
  #   addons:
  #     apt:
  #       sources:
  #         - ubuntu-toolchain-r-test
  #         - llvm-toolchain-trusty-4.0
  #       packages:
  #         - clang-4.0
  #         - xorg-dev
  #         - libglu1-mesa-dev
  #   script:
  #     - cmake -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0 ..
  #     - make
  #     - make test

  #
  # XCode 9.1
  #
  # - os: osx
  #   env:
  #     - TEST="XCode 9.1"
  #   osx_image: xcode9.1
  #   script:
  #     - cmake ..
  #     - make
  #     - make test

notifications:
  email: false

# examples
# https://github.com/Microsoft/GSL/blob/master/.travis.yml
# https://github.com/paulmenzel/brotli/blob/master/.travis.yml
# https://github.com/ainfosec/ci_helloworld/blob/master/.travis.yml
# https://github.com/neovim/neovim/blob/master/.travis.yml
