image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

cache:
  - C:\cmake-3.9.1-win32-x86

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.9.1-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.9/cmake-3.9.1-win32-x86.zip'
        7z x -y cmake-3.9.1-win32-x86 -oC:\
      }
      $env:PATH="C:\cmake-3.9.1-win32-x86\bin;$env:PATH"

before_build:
  - ps: |
      git submodule update --init --recursive
      mkdir build
      cd build
      $env:generator="Visual Studio 15 2017"
      if ($env:PLATFORM -eq "x64"){
        $env:generator="$env:generator Win64"
      }
      echo generator=$env:generator
      cmake .. -G "$env:generator"

build_script:
  - cmd: >-
    cmake --build . --config %CONFIGURATION% -- /m /v:minimal

deploy: off
